# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options
image: ubuntu:20.04.1

before_script:
  - echo "Before script section"
  - apt-get update
  - apt-get install -y qemu-system-i386
  - apt-get install -y gcc
  - apt-get install -y make
  - apt-get install -y perl
  - apt-get install -y libbinutils
  - cd src/utils
  - PATH=$PATH:`pwd`
  - cd ../..
  - echo "End of Before script section"

after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Test if we can boot"
    - cd src/vm
    - make clean
    - make
    - cd build
    - make check
    - make grade
#    - make tests/userprog/args-none.output
#    - perl -I../.. ../../tests/userprog/args-none.ck tests/userprog/args-none tests/userprog/args-none.result
