# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options
image: ubuntu:18.04

before_script:
  - echo "Before script section"
  - apt-get update
  - apt-get install -y qemu-system-i386
  - apt-get install -y gcc
  - apt-get install -y make
  - apt-get install -y perl
  - echo "End of Before script section"

after_script:
  - echo "After script section"

build1:
  stage: build
  script:
    - echo "Do your build here"
    - cd src/vm
    - make clean

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
    - make check
    - make grade
